### ISSUE TITLE
Slider doesn't slide (move) left or right.

### ISSUE THREAD

**Issue by Mustafa-Altameemi** [Mindinventory/slider_controller#5] opened 2023-05-02 13:20 UTC
### Thanks for your effort, however, the slider doesn't move at all, I don't know why!.

My Code:-

```
      Container(
            padding: const EdgeInsets.fromLTRB(30, 30, 30, 30),
            child: SliderController(
              value: 100.0,
              isDraggable: true,
              onChanged: (value) {
               // developer.log('Slider Value : $value');
              },
              min: 50.0,
              max: 150.0,
              sliderDecoration: SliderDecoration(
                inactiveColor: const Color(0xFF1A2942),
                activeColor: const Color(0xFF2BA1C3),
                thumbColor: const Color(0xFF1E7893),
                borderRadius: 20.0,
                height: 50.0,
                isThumbVisible: true,
                thumbHeight: 25.0,
                thumbWidth: 5.0,
              ),
            ),
          ),
```

**Comment by mohit-chauhan-mi** [comment] 2023-05-03 11:42
@Mustafa-Altameemi I've checked with your code it's working fine, please check it from your end.
Check with this example code,

```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.fromLTRB(30, 30, 30, 30),
        child: SliderController(
          value: 100.0,
          isDraggable: true,
          onChanged: (value) {
            // developer.log('Slider Value : $value');
          },
          min: 50.0,
          max: 150.0,
          sliderDecoration: SliderDecoration(
            inactiveColor: const Color(0xFF1A2942),
            activeColor: const Color(0xFF2BA1C3),
            thumbColor: const Color(0xFF1E7893),
            borderRadius: 20.0,
            height: 50.0,
            isThumbVisible: true,
            thumbHeight: 25.0,
            thumbWidth: 5.0,
          ),
        ),
      ),
    );
  }
}
```

Closing this because the issue is not generating.

**Closed as completed by mohit-chauhan-mi** 2023-05-03 11:42 UTC

**Comment by Mustafa-Altameemi** [comment] 2023-05-04 14:22
![2023-05-04_172542](https://user-images.githubusercontent.com/10961278/236237606-e7e3184e-3d27-4b0a-af9a-8120db129199.jpg)
@mohit-chauhan-mi Thanks for the fast reply .. I have used the same code as yours but still the same issue. 
Here is all screen:-



```
import 'package:flutter/material.dart';
import 'package:flutter_neumorphic/flutter_neumorphic.dart';
import 'package:slider_controller/slider_controller.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';
import '../widgets/widget_slider_drawer.dart';

class VideoStreamTab extends StatefulWidget {
  const VideoStreamTab({Key? key}) : super(key: key);

  @override
  State<VideoStreamTab> createState() => _VideoStreamTabState();
}

class _VideoStreamTabState extends State<VideoStreamTab> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
        body: CustomSliderDrawer(screenName: 'TV', screenDesign: _UI()));
  }
}

class _UI extends StatefulWidget {
  const _UI({Key? key}) : super(key: key);

  @override
  State<_UI> createState() => _UIState();
}

class _UIState extends State<_UI> {
  /*Vars*/
  //double _sliderValue = 30.0;
  double _value = 70.0;

  @override
  Widget build(BuildContext context) {
    return Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisSize: MainAxisSize.max,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [

          Container(
              padding: const EdgeInsets.fromLTRB(30, 30, 30, 30),
              child: SliderController(
                  value: 20.0,
                  isDraggable: true,
                  onChanged: (value) {
                    // developer.log('Slider Value : $value');
                  },
                  min: 0.0,
                  max: 100.0,
                  sliderDecoration: SliderDecoration(
                    inactiveColor: const Color(0xFF1A2942),
                    activeColor: const Color(0xFF2BA1C3),
                    thumbColor: const Color(0xFF1E7893),
                    borderRadius: 20.0,
                    height: 50.0,
                    isThumbVisible: true,
                    thumbHeight: 25.0,
                    thumbWidth: 5.0,
                  ))),

          const SizedBox(
            height: 80,
            width: double.infinity,
          ),

          //Child 2
          SfSlider(
            min: 0.0,
            max: 100.0,
            value: _value,
            interval: 20,
            showTicks: false,
            showLabels: false,
            enableTooltip: false,
            minorTicksPerInterval: 1,
            onChanged: (dynamic value) {
              setState(() {
                _value = value;
              });
            },
          ),

          const SizedBox(
            height: 80,
            width: double.infinity,
          ),
        ]);
  }
}
```

**Comment by mohit-chauhan-mi** [comment] 2023-05-05 06:06
https://user-images.githubusercontent.com/71555515/236387096-0d905ac1-5687-4f16-a786-b3238500eed0.mov

@Mustafa-Altameemi I've used your code it's working as expected can you please tell us more about what you want to achieve ?

**Comment by Mustafa-Altameemi** [comment] 2023-05-06 18:18
I have a drawer as shown in the video below and I'm trying to pick the best suitable slider.
 
Note:-
- The drawer can be opened by **swiping** from right to left (Not only using the button)
- The phone supports backward **gestures** as well. 

https://user-images.githubusercontent.com/10961278/236640430-1dc065fa-c945-44a0-83bc-55e3b1c99b74.mp4
